# Copyright 2022 the Kubeapps contributors
# SPDX-License-Identifier: Apache-2.0

---
name: "GKE e2e Tests"
description: "Run the Kubeapps e2e tests in a GKE cluster"

inputs:
  GCLOUD_KEY:
    required: true
  GKE_ADMIN:
    required: true
  # TODO(bjesus): right now it contains just the version number (eg. 1.22), rename to GKE_VERSION once CircleCI is decommissioned
  GKE_BRANCH:
    type: string
    description: "The branch of the GKE environment in which we want to test."
  GKE_RELEASE_CHANNEL:
    type: string
  IMG_DEV_TAG:
    type: string
  IMG_MODIFIER:
    type: string
  IMG_PREFIX:
    type: string
  TEST_LATEST_RELEASE:
    type: boolean
    required: false
    default: false
  TEST_TIMEOUT_MINUTES:
    type: number
    required: false
    default: 6
  USE_MULTICLUSTER_OIDC_ENV:
    type: boolean
    required: false
    default: false

jobs:
  using: composite
  env:
    GCLOUD_KEY: ${{ inputs.GCLOUD_KEY }}
    GKE_ADMIN: ${{ inputs.GKE_ADMIN }}
    GKE_BRANCH: ${{ inputs.GKE_BRANCH }}
    GKE_RELEASE_CHANNEL: ${{ inputs.GKE_RELEASE_CHANNEL }}
    IMG_DEV_TAG: ${{ inputs.IMG_DEV_TAG }}
    IMG_MODIFIER: ${{ inputs.IMG_MODIFIER }}
    IMG_PREFIX: ${{ inputs.IMG_PREFIX }}
    TEST_LATEST_RELEASE: ${{ inputs.TEST_LATEST_RELEASE }}
    TEST_TIMEOUT_MINUTES: ${{ inputs.TEST_TIMEOUT_MINUTES }}
    USE_MULTICLUSTER_OIDC_ENV: ${{ inputs.USE_MULTICLUSTER_OIDC_ENV }}
  steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: |
        set -euo pipefail
        source ./script/lib/libcitools.sh
        installGCloudSDK
        configureGCloud "${GKE_PROJECT}" "${GCLOUD_KEY}"
        installKubectl "${KUBECTL_VERSION}"
        installHelm "${HELM_VERSION_MIN}"
        installHelm "${HELM_VERSION_STABLE}" helm-stable
        exportEscapedGKEClusterName "${GKE_CLUSTER}" "${GKE_RELEASE_CHANNEL}" "${GITHUB_REF_NAME}" "${TEST_LATEST_RELEASE}" "${DEV_MODE}"
    - name: Start GKE environment
      shell: bash
      run: |
        set -euo pipefail
        ./script/start-gke-env.sh "${ESCAPED_GKE_CLUSTER}" "${GKE_ZONE}" "${GKE_BRANCH}" "${GKE_ADMIN}" > /dev/null
    - # TODO(castelblanque) Unify shared resources with kubeapps-local-dev-users-rbac.yaml that only applies to Kind clusters
      name: Apply customizations to GKE cluster
      shell: bash
      run: |
        kubectl create namespace kubeapps-user-namespace
        ./script/install-nginx.sh
    - name: "Run e2e tests script"
      env:
        TESTS_GROUP: "all"
      shell: bash
      run: ./script/run_e2e_tests.sh
    - name: 'Upload Artifacts'
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: gke_${{ inputs.GKE_RELEASE_CHANNEL }}_e2e_tests_reports
        path: integration/reports
    - name: "Delete GKE cluster"
      if: always()
      shell: bash
      run: |
        set -euo pipefail
        source ./script/lib/libcitools.sh
        deleteGKECluster "${GKE_ZONE}" "${ESCAPED_GKE_CLUSTER}"
